### PR TITLE
Look throw class hierarchy to find the HttpStatus and the Error Code

### PR DESCRIPTION
**Pull request by rubensa**
This allows to define an override for the `HttpStatus` for any **Exception** class in a class hierarchy.

For example, you could have some exceptions like `com.acme.EntiyOneNotFoundException` and `com.acme.EntityTwoNotFoundExtension` both of them extending `com.acme.NotFoundException`.

Now you can set the same `HttpStatus` for any child of `com.acme.NotFoundException` by specifying:

`error.handling.http-statuses.com.acme.NotFoundException=not_found`

If there is a new `com.acme.EntityThreeNotFoundException` it also "inherits" it's "ancestor" `HttpStatus`, but you could set:

`error.handling.http-statuses.com.acme.EntityThreeNotFoundException=bad_request`

and that would "override" it's parent settings.

### CODE REVIEW

**Comment by wimdeblauwe** [comment]
Interesting idea, but if we do this, we should search the full parent hierarchy, classes and interfaces. I am also wondering if we should add a flag to enable this behaviour, as it can be quite a work to check all parent classes and interfaces for each exception.

**Comment by wimdeblauwe** [comment]
Also, we should make this consistent for the codes and the messages as well. We can't implement it just for the http status alone.

**Comment by rubensa** [comment]
> Interesting idea, but if we do this, we should search the full parent hierarchy, classes and interfaces. I am also wondering if we should add a flag to enable this behaviour, as it can be quite a work to check all parent classes and interfaces for each exception.

Looking "only" the class hierarchy is easy (as is a "line").  If you want to search for the interfaces then it's far more complicated.  In what "order" you should search the classes and the interfaces?  Imagine your class implements two interface and each one has an HttpStatus defined.  Which one would you take?  (this is not a problem with inheritance as you can only extend one class).  This can be much more complicated with multiple interface implementation where the interfaces also extends multiple interfaces.

As for the work to check all parent classes, I don't think It should be much problem as you only have to check when an error occurs and you stop trasversing the hierarchy as soon as you find a match.

**Comment by rubensa** [comment]
> Also, we should make this consistent for the codes and the messages as well. We can't implement it just for the http status alone.

For the codes, I can implement the same strategy used for the `HttpResponse` (search in the hierarchy).
For me message override...  is not implemented in the `DefaultFallbackApiExceptionHandler` which looks like a bug?
I can implement it like in `AbstractApiExceptionHandler` and then use se same strategy used for the `HttpResponse`.

What do you think @wimdeblauwe ?

**Comment by rubensa** [comment]
> > Also, we should make this consistent for the codes and the messages as well. We can't implement it just for the http status alone.
> 
> For the codes, I can implement the same strategy used for the `HttpResponse` (search in the hierarchy).
> For me message override... is not implemented in the `DefaultFallbackApiExceptionHandler` which looks like a bug?
> I can implement it like in `AbstractApiExceptionHandler` and then use se same strategy used for the `HttpResponse`.
> 
> What do you think @wimdeblauwe ?

Uppsss... looking the code indeed currently you can only override the error message for `ConstraintViolationException` and `MethodArgumentNotValid` but not for other exceptions.

**Comment by rubensa** [comment]
> > > Also, we should make this consistent for the codes and the messages as well. We can't implement it just for the http status alone.
> > 
> > 
> > For the codes, I can implement the same strategy used for the `HttpResponse` (search in the hierarchy).
> > For me message override... is not implemented in the `DefaultFallbackApiExceptionHandler` which looks like a bug?
> > I can implement it like in `AbstractApiExceptionHandler` and then use se same strategy used for the `HttpResponse`.
> > What do you think @wimdeblauwe ?
> 
> Uppsss... looking the code indeed currently you can only override the error message for `ConstraintViolationException` and `MethodArgumentNotValid` but not for other exceptions.

Checking this I also realized that you can't override by configuration the HttpStatus for any of the predefined (and preregistered) handlers.

**Comment by rubensa** [comment]
Examining a bit more, the override mechanism looks "strange".
Usually, the precedence is like this:

- Configuration by properties has the higher priority
- Configuration by annotation is next
- Then default configuration by code

For example for the error code there should be de default one by code, that is use the class name.  Then you could "override" this behavior by adding a specific annotation to your exception class.  An then, you can "override" this by a configuration property.

But the actual implementation is that if your class has an annotation then that is used and only if not present the configuration property is checked and, if no configuration property is present, configure by code (where de code strategy can also be configured by properties)

```java
    private String getErrorCode(Throwable exception) {
        ResponseErrorCode errorCodeAnnotation = AnnotationUtils.getAnnotation(exception.getClass(), ResponseErrorCode.class);
        String code;
        if (errorCodeAnnotation != null) {
            code = errorCodeAnnotation.value();
        } else {
            String exceptionClassName = exception.getClass().getName();
            if (properties.getCodes().containsKey(exceptionClassName)) {
                code = replaceCodeWithConfiguredOverrideIfPresent(exceptionClassName);
            } else {
                switch (properties.getDefaultErrorCodeStrategy()) {
                    case FULL_QUALIFIED_NAME:
                        code = exception.getClass().getName();
                        break;
                    case ALL_CAPS:
                        code = convertToAllCaps(exception.getClass().getSimpleName());
                        break;
                    default:
                        throw new IllegalArgumentException("Unknown default error code strategy: " + properties.getDefaultErrorCodeStrategy());
                }
            }
        }

        return code;
    }
```

**Comment by rubensa** [comment]
Also make note that the name of the method `replaceCodeWithConfiguredOverrideIfPresent` does not make sense as there is a check for the presence of the configuration before calling and If there could exists the case to call this method without checking then the implementations is not using the ErrorCodeStrategy.

```java
    private String replaceCodeWithConfiguredOverrideIfPresent(String code) {
        return properties.getCodes().getOrDefault(code, code);
    }
```

**Comment by rubensa** [comment]
Updated `DefaultFallbackApiExceptionHandler` to search the error codes in the hierarchy.
Also the override order has been fixed (for `ErrorCode` and **HttpStatus**) and the method `replaceCodeWithConfiguredOverrideIfPresent` has been removed.
Now both the override by propertly or by annotation is checked in the hierarchy.

**Comment by rubensa** [comment]
Make a rebase on develop branch branch.

**Comment by rubensa** [comment]
Remove commit included in master but not in develop (added by mistake on the rebase).

**Comment by wimdeblauwe** [comment]
Thank you for the thorough analysis! 

First of all, the target branch of the PR should `develop`, not `master`. Ongoing work is done on `develop` until the release is done after which I merge to `master`. This ensures that the doc site remains relevant for the currently released version.

Next, I don't want to mix 2 changes. Your observations are probably correct that the override mechanisms are not consistent at present. I'll look into it in more detail the coming weeks to know how the order should be and how we best ensure this order is consistent for everything. I think we should do this in a separate PR as it has nothing to do with following the superclases (and/or super interfaces) or not.

Thanks again for your contribution, but please try to be patient until I find the time to thoroughly investigate this further.

**Comment by wimdeblauwe** [comment]
I created issue #22 to tackle the inconsistency in the override order.

**Comment by wimdeblauwe** [comment]
I would love if you could take a look at my PR #23. This should fix the precedence of the override and also allow override for the http status, error code and error message for the built-in handlers as well.

**Comment by wimdeblauwe** [comment]
PR #23 is merged now. Can you redo only the changes looking for the super class starting from the current `develop` branch? If it easier, you can abandon this PR and create a new one.

**Comment by rubensa** [comment]
Closed in favor of #24

**Comment by rubensa** [comment]
#24 closed in favor of #25

**Pull request closed without merging**
