### PR TITLE
Add support for Spring Reactive Web Flux

### PR DESCRIPTION
**Pull request by wimdeblauwe**

### CODE REVIEW

**Comment by wimdeblauwe** [comment]
I believe the code is in good shape to release a first release candidate. Because this is a big change, it will be good to not fully release immediately, but get some early feedback hopefully. Can you have another look if you think of anything else we should tacle @fabiomarini ?

**Comment by fabiomarini** [comment]
I agree with you, even if the code looks good, it better to keep it in test mode for a few days to see if there are other requirements or corner cases not yet covered.
I'll be using the reactive features in one of my current projects starting from next week so I'll keep you updated on every possible addition or fix.

**Comment by fabiomarini** [comment]
Just added a small fix to the `testPostWithValidationError` test because it only works if you are on the right Locale.
I added the `@BeforeEach` method to set the US Locale.

**Comment by wimdeblauwe** [comment]
Did you push that commit to this PR, because I don't see that commit?

**Pull request merged**
